"use client";
import { useState } from "react";
import Link from "next/link";
type Question = { id: string; questionText: string; options: string[] };
type Result = { questionId: string; selectedAnswer: string; correctAnswer: string; explanation: string | null; isCorrect: boolean };
export default function CourseQuizClient({ courseId, courseTitle, questions }: { courseId: string; courseTitle: string; questions: Question[] }) {
  const [answers, setAnswers] = useState<Record<string, string>>({}); const [results, setResults] = useState<Result[]>([]); const [score, setScore] = useState<number | null>(null); const [error, setError] = useState(""); const [certificateId, setCertificateId] = useState("");
  async function submit() { const response = await fetch(`/api/courses/${courseId}/quiz`, { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ answers: Object.entries(answers).map(([questionId, selectedAnswer]) => ({ questionId, selectedAnswer })) }) }); const data = await response.json(); if (!response.ok) { setError(data.error || "Could not submit quiz"); return; } setResults(data.results); setScore(data.score); if (data.certificateId) setCertificateId(data.certificateId); }
  return <main className="min-h-screen bg-slate-950 p-6 text-slate-100 md:p-12"><div className="mx-auto max-w-3xl space-y-6"><Link href="/university" className="text-sm text-slate-400">← Course catalog</Link><h1 className="font-serif text-3xl font-bold text-amber-400">{courseTitle} quiz</h1>{questions.map((question) => { const result = results.find((item) => item.questionId === question.id); return <section key={question.id} className="space-y-3 rounded-xl border border-slate-800 bg-slate-900 p-6"><h2 className="text-lg font-semibold">{question.questionText}</h2>{question.options.map((option) => <label key={option} className="flex min-h-12 cursor-pointer items-center gap-3 rounded-lg border border-slate-700 px-4"><input type="radio" name={question.id} value={option} checked={answers[question.id] === option} disabled={score !== null} onChange={() => setAnswers({ ...answers, [question.id]: option })}/>{option}{result?.correctAnswer === option && <span className="ml-auto text-emerald-400">Correct</span>}</label>)}{result && <p className={result.isCorrect ? "text-emerald-300" : "text-rose-300"}>{result.explanation}</p>}</section>; })}{error && <p role="alert" className="text-red-300">{error}</p>}{score === null ? <button disabled={!questions.length || Object.keys(answers).length !== questions.length} onClick={() => void submit()} className="min-h-12 rounded-lg bg-amber-500 px-5 font-semibold text-slate-950 disabled:opacity-50">Submit quiz</button> : <div className="space-y-3"><p className="text-xl font-semibold">Score: {score}/{questions.length}</p>{certificateId && <Link className="inline-flex rounded-lg bg-amber-500 px-4 py-3 font-semibold text-slate-950" href={`/certificates/${certificateId}`}>View / download certificate</Link>}</div>}</div></main>;
}
