"use client";
import { FormEvent, useState } from "react";
import Link from "next/link";
import { signInWithApple, signInWithEmail, signInWithGoogle, signUpWithEmail } from "@/lib/firebase/auth-helpers";

export default function LoginPage() {
  const [mode, setMode] = useState<"signin" | "signup">("signup"); const [email, setEmail] = useState(""); const [password, setPassword] = useState(""); const [country, setCountry] = useState("NG"); const [error, setError] = useState(""); const [busy, setBusy] = useState(false);
  async function syncSession(credential: Awaited<ReturnType<typeof signInWithEmail>>, saveCountry = false) { const idToken = await credential.user.getIdToken(true); const response = await fetch("/api/auth/session", { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ idToken }) }); if (!response.ok) throw new Error("Could not create a secure session"); if (saveCountry) await fetch("/api/auth/country", { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ country }) }); window.location.assign("/highschool"); }
  async function submit(e: FormEvent) { e.preventDefault(); setBusy(true); setError(""); try { const credential = mode === "signup" ? await signUpWithEmail(email, password) : await signInWithEmail(email, password); await syncSession(credential, mode === "signup"); } catch (e) { setError(e instanceof Error ? e.message : "Could not authenticate"); } finally { setBusy(false); } }
  async function social(provider: "google" | "apple") { setError(""); try { const credential = provider === "google" ? await signInWithGoogle() : await signInWithApple(); await syncSession(credential); } catch (e) { setError(e instanceof Error ? e.message : "Could not authenticate"); } }
  return <main className="min-h-screen bg-slate-950 p-6 text-slate-100"><div className="mx-auto mt-10 max-w-md space-y-6 rounded-2xl border border-slate-800 bg-slate-900 p-7"><Link href="/" className="text-sm text-slate-400">← Home</Link><div><h1 className="font-serif text-3xl font-bold text-amber-400">{mode === "signup" ? "Create your account" : "Welcome back"}</h1><p className="mt-2 text-sm text-slate-400">Your learning progress syncs across devices.</p></div><form onSubmit={(e) => void submit(e)} className="space-y-4"><label className="block text-sm">Email<input type="email" required value={email} onChange={(e) => setEmail(e.target.value)} className="mt-2 min-h-12 w-full rounded-lg border border-slate-700 bg-slate-950 px-3"/></label><label className="block text-sm">Password<input type="password" minLength={6} required value={password} onChange={(e) => setPassword(e.target.value)} className="mt-2 min-h-12 w-full rounded-lg border border-slate-700 bg-slate-950 px-3"/></label>{mode === "signup" && <label className="block text-sm">Country<select value={country} onChange={(e) => setCountry(e.target.value)} className="mt-2 min-h-12 w-full rounded-lg border border-slate-700 bg-slate-950 px-3"><option value="NG">Nigeria</option><option value="GH">Ghana</option><option value="KE">Kenya</option><option value="IN">India</option><option value="PK">Pakistan</option><option value="GB">United Kingdom</option><option value="US">United States</option><option value="EU">Europe</option></select></label>}<button disabled={busy} className="min-h-12 w-full rounded-lg bg-amber-500 font-semibold text-slate-950 disabled:opacity-50">{busy ? "Please wait…" : mode === "signup" ? "Sign up" : "Sign in"}</button></form><div className="grid grid-cols-2 gap-3"><button onClick={() => void social("google")} className="min-h-11 rounded-lg border border-slate-700">Continue with Google</button><button onClick={() => void social("apple")} className="min-h-11 rounded-lg border border-slate-700">Continue with Apple</button></div>{error && <p role="alert" className="text-sm text-red-300">{error}</p>}<p className="text-sm text-slate-400">{mode === "signup" ? "Already registered?" : "New to Gnostiri?"} <button onClick={() => setMode(mode === "signup" ? "signin" : "signup")} className="text-teal-300 underline">{mode === "signup" ? "Sign in" : "Create an account"}</button></p></div></main>;
}
