"use client";
import { useEffect, useState } from "react";
import Link from "next/link";
import { useAuth } from "@/context/AuthContext";

const displays: Record<string, [string, string]> = { NG: ["₦2,500 / month", "₦25,000 / year"], GH: ["GH₵35 / month", "GH₵350 / year"], KE: ["KSh 350 / month", "KSh 3,500 / year"], IN: ["₹199 / month", "₹1,999 / year"], PK: ["₨500 / month", "₨5,000 / year"], US: ["$3.99 / month", "$39.99 / year"], GB: ["£3.99 / month", "£39.99 / year"], EU: ["€3.99 / month", "€39.99 / year"] };
export default function PricingPage() {
  const { user } = useAuth(); const [period, setPeriod] = useState("monthly"); const [error, setError] = useState(""); const [busy, setBusy] = useState(false); const [country, setCountry] = useState("US");
  useEffect(() => { if (user) fetch("/api/auth/country").then((r) => r.json()).then((d) => { if (d.country) setCountry(d.country); }).catch(() => undefined); }, [user]);
  async function checkout() { if (!user) { setError("Sign in before starting checkout."); return; } setBusy(true); setError(""); try { const res = await fetch("/api/payments/checkout", { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ period }) }); const data = await res.json(); if (!res.ok) throw new Error(data.error); window.location.href = data.checkoutUrl; } catch (e) { setError(e instanceof Error ? e.message : "Checkout unavailable"); setBusy(false); } }
  return <main className="min-h-screen bg-transparent p-6 text-slate-100 md:p-12"><div className="mx-auto max-w-4xl space-y-7"><Link href="/university" className="text-slate-400">← University</Link><h1 className="font-serif text-4xl font-bold text-amber-400">Gnostiri Premium</h1><p className="text-slate-300">Unlock university courses, adaptive plans, certificates, and unlimited Tutor access.</p><div className="flex gap-2"><button onClick={() => setPeriod("monthly")} className={`rounded-lg px-4 py-2 ${period === "monthly" ? "bg-amber-500 text-slate-950" : "bg-slate-800"}`}>Monthly</button><button onClick={() => setPeriod("annual")} className={`rounded-lg px-4 py-2 ${period === "annual" ? "bg-amber-500 text-slate-950" : "bg-slate-800"}`}>Annual</button></div><section className="rounded-2xl border border-slate-700 bg-slate-900 p-7"><p className="text-sm text-slate-400">Localized pricing</p><h2 className="mt-2 text-3xl font-bold">{(displays[country] || displays.US)[period === "annual" ? 1 : 0]}</h2><ul className="my-6 list-inside list-disc space-y-2 text-slate-300"><li>All university courses and quizzes</li><li>Unlimited AI Tutor</li><li>Adaptive study plans and completion certificates</li></ul><button onClick={() => void checkout()} disabled={busy} className="min-h-12 rounded-lg bg-amber-500 px-5 font-bold text-slate-950 disabled:opacity-50">{busy ? "Starting checkout…" : "Subscribe"}</button>{error && <p role="alert" className="mt-3 text-red-300">{error}</p>}</section></div></main>;
}
